name: Deploy Frontend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Install dependencies and build the React app
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      # 3️⃣ Create a clean deployment package
      - name: Generate deployment package
        run: |
          # Only include files needed for Docker build and deployment
          zip -r deploy.zip Dockerfile nginx.conf build/ package.json package-lock.json

      # 4️⃣ Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: frontend
          environment_name: Frontend-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-518890434707
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
